apiDir: "../headless-commerce-delivery-cart-api/src/main/java"
apiPackagePath: "com.liferay.headless.commerce.delivery.cart"
application:
    baseURI: "/headless-commerce-delivery-cart"
    className: "HeadlessCommerceDeliveryCartApplication"
    name: "Liferay.Headless.Commerce.Delivery.Cart"
author: "Andrea Sbarra"
clientDir: "../headless-commerce-delivery-cart-client/src/main/java"
forcePredictableSchemaPropertyName: false
testDir: "../headless-commerce-delivery-cart-test/src/testIntegration/java"