components:
  schemas:
    AggregateRating:
      description: https://www.schema.org/AggregateRating
      properties:
        bestRating:
          type: number
        id:
          format: int64
          type: integer
        ratingCount:
          type: number
        ratingValue:
          type: number
        worstRating:
          type: number
      type: object
    BlogPosting:
      description: https://www.schema.org/BlogPosting
      properties:
        aggregateRating:
          $ref: "#/components/schemas/AggregateRating"
        alternativeHeadline:
          type: string
        articleBody:
          type: string
        caption:
          type: string
        category:
          items:
            format: int64
            type: integer
          type: array
        comment:
          items:
            $ref: "#/components/schemas/Comment"
          type: array
        contentSpace:
          format: int64
          type: integer
        creator:
          $ref: "#/components/schemas/Creator"
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        datePublished:
          format: date-time
          type: string
        description:
          type: string
        encodingFormat:
          type: string
        friendlyUrlPath:
          type: string
        headline:
          type: string
        id:
          format: int64
          type: integer
        image:
          allOf:
            - $ref: "#/components/schemas/ImageObject"
          readOnly: true
        imageId:
          format: int64
          type: integer
          writeOnly: true
        keywords:
          items:
            type: string
          type: array
        repository:
          allOf:
            - $ref: "#/components/schemas/ImageObjectRepository"
          readOnly: true
        repositoryId:
          format: int64
          type: integer
          writeOnly: true
      type: object
    Comment:
      description: https://www.schema.org/Comment
      properties:
        comments:
          items:
            $ref: "#/components/schemas/Comment"
          type: array
        creator:
          $ref: "#/components/schemas/Creator"
        id:
          format: int64
          type: integer
        text:
          type: string
      type: object
    Creator:
      description: https://www.schema.org/Creator
      properties:
        additionalName:
          type: string
        familyName:
          type: string
        givenName:
          type: string
        id:
          format: int64
          type: integer
        image:
          format: uri
          type: string
        name:
          type: string
        profileURL:
          format: uri
          type: string
      type: object
    ImageObject:
      description: https://www.schema.org/ImageObject
      properties:
        contentUrl:
          type: string
        encodingFormat:
          type: string
        fileExtension:
          type: string
        id:
          format: int64
          type: integer
        sizeInBytes:
          type: number
        title:
          type: string
      type: object
    ImageObjectRepository:
      description: https://www.schema.org/ImageObjectRepository
      properties:
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        id:
          format: int64
          type: integer
        images:
          items:
            $ref: "#/components/schemas/ImageObject"
          readOnly: true
          type: array
        imagesIds:
          items:
            format: int64
            type: integer
          type: array
          writeOnly: true
        name:
          type: string
      type: object
info:
  description: ""
  title: ""
  version: v1.0
openapi: 3.0.1
paths:
  "/aggregate-ratings/{aggregate-rating-id}":
    get:
      parameters:
        - in: path
          name: aggregate-rating-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AggregateRating"
          description: ""
      tags: ["AggregateRating"]
  "/blog-postings/{blog-posting-id}":
    delete:
      parameters:
        - in: path
          name: blog-posting-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
      tags: ["BlogPosting"]
    get:
      parameters:
        - in: path
          name: blog-posting-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlogPosting"
          description: ""
      tags: ["BlogPosting"]
    put:
      parameters:
        - in: path
          name: blog-posting-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BlogPosting"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlogPosting"
          description: ""
      tags: ["BlogPosting"]
  "/blog-postings/{blog-posting-id}/categories":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: blog-posting-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  format: int64
                  type: integer
                type: array
          description: ""
      tags: ["BlogPosting"]
    post:
      parameters:
        - in: path
          name: blog-posting-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              format: int64
              type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: ""
      tags: ["BlogPosting"]
  "/blog-postings/{blog-posting-id}/categories/batch-create":
    post:
      parameters:
        - in: path
          name: blog-posting-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              format: int64
              type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: ""
      tags: ["BlogPosting"]
  "/blog-postings/{blog-posting-id}/comments":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: blog-posting-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""
      tags: ["Comment"]
  "/comments/{comment-id}":
    get:
      parameters:
        - in: path
          name: comment-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
          description: ""
      tags: ["Comment"]
  "/comments/{comment-id}/comments":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: comment-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""
      tags: ["Comment"]
  "/content-spaces/{content-space-id}/blog-postings":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/BlogPosting"
                type: array
          description: ""
      tags: ["BlogPosting"]
    post:
      parameters:
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BlogPosting"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlogPosting"
          description: ""
      tags: ["BlogPosting"]
  "/content-spaces/{content-space-id}/blog-postings/batch-create":
    post:
      parameters:
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BlogPosting"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlogPosting"
          description: ""
      tags: ["BlogPosting"]
  "/image-object-repositories/{image-object-repository-id}":
    get:
      parameters:
        - in: path
          name: image-object-repository-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageObjectRepository"
          description: ""
      tags: ["ImageObjectRepository"]
  "/image-object-repositories/{image-object-repository-id}/image-objects":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: image-object-repository-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ImageObject"
                type: array
          description: ""
      tags: ["ImageObject"]
    post:
      parameters:
        - in: path
          name: image-object-repository-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImageObject"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageObject"
          description: ""
      tags: ["ImageObject"]
  "/image-object-repositories/{image-object-repository-id}/image-objects/batch-create":
    post:
      parameters:
        - in: path
          name: image-object-repository-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImageObject"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageObject"
          description: ""
      tags: ["ImageObject"]
  "/image-objects/{image-object-id}":
    delete:
      parameters:
        - in: path
          name: image-object-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
      tags: ["ImageObject"]
    get:
      parameters:
        - in: path
          name: image-object-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageObject"
          description: ""
      tags: ["ImageObject"]