apiDir: "../bulk-rest-api/src/main/java"
apiPackagePath: "com.liferay.bulk.rest"
application:
    baseURI: "/bulk"
    className: "BulkRESTApplication"
    name: "Liferay.Bulk.REST"
author: "Alejandro Tardín"
testDir: "../bulk-rest-test/src/testIntegration/java"