components:
    schemas:
        ChangeTransition:
            description: https://www.schema.org/ChangeTransition
            properties:
                transition:
                    type: string
            type: object
        Creator:
            description: https://www.schema.org/Creator
            properties:
                additionalName:
                    type: string
                familyName:
                    type: string
                givenName:
                    type: string
                id:
                    format: int64
                    type: integer
                image:
                    format: uri
                    type: string
                name:
                    type: string
                profileURL:
                    format: uri
                    type: string
            type: object
        ObjectReviewed:
            description: https://www.schema.org/ObjectReviewed
            properties:
                id:
                    format: int64
                    type: integer
                resourceType:
                    type: string
            type: object
        WorkflowLog:
            description: https://www.schema.org/WorkflowLog
            properties:
                auditPerson:
                    $ref: "#/components/schemas/Creator"
                commentLog:
                    type: string
                dateCreated:
                    format: date-time
                    type: string
                id:
                    format: int64
                    type: integer
                person:
                    $ref: "#/components/schemas/Creator"
                previousPerson:
                    $ref: "#/components/schemas/Creator"
                previousState:
                    type: string
                state:
                    type: string
                taskId:
                    format: int64
                    type: integer
                type:
                    type: string
            type: object
        WorkflowTask:
            description: https://www.schema.org/WorkflowTask
            properties:
                completed:
                    type: boolean
                dateCompleted:
                    format: date-time
                    type: string
                dateCreated:
                    format: date-time
                    type: string
                definitionName:
                    type: string
                description:
                    type: string
                dueDate:
                    format: date-time
                    type: string
                id:
                    format: int64
                    type: integer
                name:
                    type: string
                objectReviewed:
                    $ref: "#/components/schemas/ObjectReviewed"
                transitions:
                    items:
                        type: string
                    type: array
            type: object
        WorkflowTaskAssignToMe:
            description: https://www.schema.org/WorkflowTaskAssignToMe
            properties:
                comment:
                    type: string
                dueDate:
                    format: date-time
                    type: string
            type: object
        WorkflowTaskAssignToUser:
            description: https://www.schema.org/WorkflowTaskAssignToUser
            properties:
                assigneeId:
                    format: int64
                    type: integer
                comment:
                    type: string
                dueDate:
                    format: date-time
                    type: string
            type: object
info:
    description: ""
    title: "Headless Workflow"
    version: v1.0
openapi: 3.0.1
paths:
    "/roles/{role-id}/workflow-tasks":
        get:
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: path
                  name: role-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/WorkflowTask"
                                type: array
                    description: ""
            tags: ["WorkflowTask"]
    "/workflow-logs/{workflow-log-id}":
        get:
            parameters:
                - in: path
                  name: workflow-log-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/WorkflowLog"
                    description: ""
            tags: ["WorkflowLog"]
    "/workflow-tasks/assigned-to-me":
        get:
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/WorkflowTask"
                                type: array
                    description: ""
            tags: ["WorkflowTask"]
    "/workflow-tasks/assigned-to-my-roles":
        get:
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/WorkflowTask"
                                type: array
                    description: ""
            tags: ["WorkflowTask"]
    "/workflow-tasks/{workflow-task-id}":
        get:
            parameters:
                - in: path
                  name: workflow-task-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/WorkflowTask"
                    description: ""
            tags: ["WorkflowTask"]
    "/workflow-tasks/{workflow-task-id}/assign-to-me":
        post:
            parameters:
                - in: path
                  name: workflow-task-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/WorkflowTaskAssignToMe"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/WorkflowTask"
                    description: ""
            tags: ["WorkflowTask"]
    "/workflow-tasks/{workflow-task-id}/assign-to-user":
        post:
            parameters:
                - in: path
                  name: workflow-task-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/WorkflowTaskAssignToUser"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/WorkflowTask"
                    description: ""
            tags: ["WorkflowTask"]
    "/workflow-tasks/{workflow-task-id}/change-transition":
        post:
            parameters:
                - in: path
                  name: workflow-task-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ChangeTransition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/WorkflowTask"
                    description: ""
            tags: ["WorkflowTask"]
    "/workflow-tasks/{workflow-task-id}/update-due-date":
        post:
            parameters:
                - in: path
                  name: workflow-task-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/WorkflowTaskAssignToMe"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/WorkflowTask"
                    description: ""
            tags: ["WorkflowTask"]
    "/workflow-tasks/{workflow-task-id}/workflow-logs":
        get:
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: path
                  name: workflow-task-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/WorkflowLog"
                                type: array
                    description: ""
            tags: ["WorkflowLog"]