components:
    schemas:
        Collection:
            properties:
                additionCount:
                    type: integer
                collectionId:
                    type: integer
                companyId:
                    format: int64
                    type: integer
                deletionCount:
                    type: integer
                description:
                    type: string
                modificationCount:
                    type: integer
                name:
                    type: string
                statusByUserName:
                    type: string
                statusDate:
                    format: date-time
                    type: string
            type: object
        CollectionUpdate:
            properties:
                description:
                    type: string
                name:
                    type: string
            type: object
        Settings:
            properties:
                changeTrackingAllowed:
                    type: boolean
                changeTrackingEnabled:
                    type: boolean
                checkoutCTCollectionConfirmationEnabled:
                    type: boolean
                companyId:
                    format: int64
                    type: integer
                supportedContentTypeLanguageKeys:
                    items:
                        type: string
                    type: array
                supportedContentTypes:
                    items:
                        type: string
                    type: array
                userId:
                    format: int64
                    type: integer
            type: object
        SettingsUpdate:
            properties:
                changeTrackingEnabled:
                    type: boolean
                checkoutCTCollectionConfirmationEnabled:
                    type: boolean
            type: object
info:
    description: ""
    title: "Change Tracking REST"
    version: v1.0
openapi: 3.0.1
paths:
    "/collections":
        get:
            operationId: getCollectionsPage
            parameters:
                - in: query
                  name: companyId
                  required: false
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: page
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: sort
                  required: false
                  schema:
                      type: string
                - in: query
                  name: type
                  required: false
                  schema:
                      default: "all"
                      type: string
                - in: query
                  name: userId
                  required: false
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Collection"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Collection"
                                type: array
                    description: ""
            tags: ["Collection"]
        post:
            operationId: postCollection
            parameters:
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CollectionUpdate"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CollectionUpdate"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Collection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Collection"
                    description: ""
            tags: ["Collection"]
    "/collections/{collectionId}":
        delete:
            operationId: deleteCollection
            parameters:
                - in: path
                  name: collectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
                404:
                    content:
                        application/json: {}
                    description: ""
            tags: ["Collection"]
        get:
            operationId: getCollection
            parameters:
                - in: path
                  name: collectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Collection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Collection"
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Collection"]
    "/collections/{collectionId}/checkout":
        post:
            operationId: postCollectionCheckout
            parameters:
                - in: path
                  name: collectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                202:
                    content:
                        application/json: {}
                    description: ""
            tags: ["Collection"]
    "/collections/{collectionId}/publish":
        post:
            operationId: postCollectionPublish
            parameters:
                - in: path
                  name: collectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: ignoreCollision
                  required: true
                  schema:
                      type: boolean
                - in: query
                  name: userId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                202:
                    content:
                        application/json: {}
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Collection"]
    "/settings":
        get:
            operationId: getSettingsPage
            parameters:
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: false
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Settings"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Settings"
                                type: array
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Settings"]
        put:
            operationId: putSettings
            parameters:
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: false
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SettingsUpdate"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SettingsUpdate"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Settings"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Settings"
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Settings"]