components:
    schemas:
        AffectedEntry:
            properties:
                contentType:
                    type: string
                title:
                    type: string
            type: object
        Collection:
            properties:
                additionCount:
                    format: int64
                    type: integer
                companyId:
                    format: int64
                    type: integer
                dateStatus:
                    format: date-time
                    type: string
                deletionCount:
                    format: int64
                    type: integer
                description:
                    type: string
                id:
                    format: int64
                    type: integer
                modificationCount:
                    format: int64
                    type: integer
                name:
                    type: string
                statusByUserName:
                    type: string
            type: object
        CollectionType:
            default: "all"
            enum: [active, all, production, recent]
            type: string
        CollectionUpdate:
            properties:
                description:
                    type: string
                name:
                    type: string
            type: object
        Process:
            properties:
                collection:
                    $ref: "#/components/schemas/Collection"
                companyId:
                    format: int64
                    type: integer
                dateCreated:
                    format: date-time
                    type: string
                id:
                    format: int64
                    type: integer
                percentage:
                    type: integer
                processUser:
                    $ref: "#/components/schemas/ProcessUser"
                status:
                    type: string
            type: object
        ProcessType:
            default: "all"
            enum: [all, failed, in_progress, published, published_latest]
            type: string
        ProcessUser:
            properties:
                userId:
                    format: int64
                    type: integer
                userInitials:
                    type: string
                userName:
                    type: string
                userPortraitURL:
                    type: string
            type: object
        Settings:
            properties:
                changeTrackingAllowed:
                    type: boolean
                changeTrackingEnabled:
                    type: boolean
                checkoutCTCollectionConfirmationEnabled:
                    type: boolean
                companyId:
                    format: int64
                    type: integer
                supportedContentTypeLanguageKeys:
                    items:
                        type: string
                    type: array
                supportedContentTypes:
                    items:
                        type: string
                    type: array
                userId:
                    format: int64
                    type: integer
            type: object
        SettingsUpdate:
            properties:
                changeTrackingEnabled:
                    type: boolean
                checkoutCTCollectionConfirmationEnabled:
                    type: boolean
            type: object
info:
    description: ""
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Change Tracking REST"
    version: v1.0
openapi: 3.0.1
paths:
    "/collections":
        get:
            operationId: getCollectionsPage
            parameters:
                - in: query
                  name: collectionType
                  required: false
                  schema:
                      $ref: "#/components/schemas/CollectionType"
                - in: query
                  name: companyId
                  required: false
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: false
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: page
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: sort
                  required: false
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Collection"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Collection"
                                type: array
                    description: ""
            tags: ["Collection"]
        post:
            operationId: postCollection
            parameters:
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CollectionUpdate"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CollectionUpdate"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Collection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Collection"
                    description: ""
                409:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
                461:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
                462:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
                463:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Collection"]
    "/collections/{collectionId}":
        delete:
            operationId: deleteCollection
            parameters:
                - in: path
                  name: collectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
                404:
                    description: ""
            tags: ["Collection"]
        get:
            operationId: getCollection
            parameters:
                - in: path
                  name: collectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Collection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Collection"
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Collection"]
    "/collections/{collectionId}/checkout":
        post:
            operationId: postCollectionCheckout
            parameters:
                - in: path
                  name: collectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                202:
                    description: ""
            tags: ["Collection"]
    "/collections/{collectionId}/publish":
        post:
            operationId: postCollectionPublish
            parameters:
                - in: path
                  name: collectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: ignoreCollision
                  required: true
                  schema:
                      type: boolean
                - in: query
                  name: userId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                202:
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Collection"]
    "/processes":
        get:
            operationId: getProcessesPage
            parameters:
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: keywords
                  required: false
                  schema:
                      type: string
                - in: query
                  name: processType
                  required: false
                  schema:
                      $ref: "#/components/schemas/ProcessType"
                - in: query
                  name: userId
                  required: false
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: page
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: sort
                  required: false
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Process"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Process"
                                type: array
                    description: ""
            tags: ["Process"]
    "/processes/users":
        get:
            operationId: getProcessUsersPage
            parameters:
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: keywords
                  required: false
                  schema:
                      type: string
                - in: query
                  name: processType
                  required: false
                  schema:
                      $ref: "#/components/schemas/ProcessType"
                - in: query
                  name: page
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  required: false
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ProcessUser"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ProcessUser"
                                type: array
                    description: ""
            tags: ["ProcessUser"]
    "/processes/{processId}":
        get:
            operationId: getProcess
            parameters:
                - in: path
                  name: processId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Process"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Process"
                    description: ""
            tags: ["Process"]
    "/settings":
        get:
            operationId: getSettingsPage
            parameters:
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: false
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Settings"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Settings"
                                type: array
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Settings"]
        put:
            operationId: putSettings
            parameters:
                - in: query
                  name: companyId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: userId
                  required: false
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SettingsUpdate"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SettingsUpdate"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Settings"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Settings"
                    description: ""
                400:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Settings"]