apiDir: "../headless-form-api/src/main/java"
apiPackagePath: "com.liferay.headless.form"
application:
    baseURI: "/headless-form"
    className: "HeadlessFormApplication"
    name: "Liferay.Headless.Form"
author: "Javier Gamarra"
clientDir: "../headless-form-client/src/main/java"
testDir: "../headless-form-test/src/testIntegration/java"