apiDir: "../headless-commerce-admin-channel-api/src/main/java"
apiPackagePath: "com.liferay.headless.commerce.admin.channel"
application:
    baseURI: "/headless-commerce-admin-channel"
    className: "HeadlessCommerceAdminChannelApplication"
    name: "Liferay.Headless.Commerce.Admin.Channel"
author: "Andrea Sbarra"
clientDir: "../headless-commerce-admin-channel-client/src/main/java"
forcePredictableOperationId: false
forcePredictableSchemaPropertyName: false
testDir: "../headless-commerce-admin-channel-test/src/testIntegration/java"