apiDir: "../headless-commerce-admin-catalog-api/src/main/java"
apiPackagePath: "com.liferay.headless.commerce.admin.catalog"
application:
    baseURI: "/headless-commerce-admin-catalog"
    className: "HeadlessCommerceAdminCatalogApplication"
    name: "Liferay.Headless.Commerce.Admin.Catalog"
author: "Zoltán Takács"
clientDir: "../headless-commerce-admin-catalog-client/src/main/java"
forcePredictableOperationId: false
forcePredictableSchemaPropertyName: false
testDir: "../headless-commerce-admin-catalog-test/src/testIntegration/java"