components:
    schemas:
        AppWorkflow:
            properties:
                appId:
                    format: int64
                    type: integer
                appVersion:
                    type: string
                appWorkflowDefinitionId:
                    format: int64
                    type: integer
                appWorkflowStates:
                    items:
                        $ref: "#/components/schemas/AppWorkflowState"
                    type: array
                appWorkflowTasks:
                    items:
                        $ref: "#/components/schemas/AppWorkflowTask"
                    type: array
            type: object
        AppWorkflowDataLayoutLink:
            properties:
                dataLayoutId:
                    format: int64
                    type: integer
                readOnly:
                    type: boolean
            type: object
        AppWorkflowDataRecordLink:
            properties:
                appWorkflow:
                    $ref: "#/components/schemas/AppWorkflow"
                dataRecordId:
                    format: int64
                    type: integer
            type: object
        AppWorkflowRoleAssignment:
            properties:
                roleId:
                    format: int64
                    type: integer
                roleName:
                    type: string
            type: object
        AppWorkflowState:
            properties:
                appWorkflowTransitions:
                    items:
                        $ref: "#/components/schemas/AppWorkflowTransition"
                    type: array
                initial:
                    type: boolean
                name:
                    type: string
            type: object
        AppWorkflowTask:
            properties:
                appWorkflowDataLayoutLinks:
                    items:
                        $ref: "#/components/schemas/AppWorkflowDataLayoutLink"
                    type: array
                appWorkflowRoleAssignments:
                    items:
                        $ref: "#/components/schemas/AppWorkflowRoleAssignment"
                    type: array
                appWorkflowTransitions:
                    items:
                        $ref: "#/components/schemas/AppWorkflowTransition"
                    type: array
                name:
                    type: string
            type: object
        AppWorkflowTransition:
            properties:
                name:
                    type: string
                primary:
                    type: boolean
                transitionTo:
                    type: string
            type: object
        DataRecordIds:
            properties:
                dataRecordIds:
                    items:
                        format: int64
                        type: integer
                    type: array
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.app.builder.workflow.rest.client', and version '1.0.3'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "App Builder Workflow"
    version: v1.0
openapi: 3.0.1
paths:
    "/apps/{appId}/app-workflows":
        delete:
            operationId: deleteAppWorkflow
            parameters:
                - in: path
                  name: appId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
                    description:
                        ""
            tags: ["AppWorkflow"]
        get:
            operationId: getAppWorkflow
            parameters:
                - in: path
                  name: appId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                    description:
                        ""
            tags: ["AppWorkflow"]
        post:
            operationId: postAppWorkflow
            parameters:
                - in: path
                  name: appId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AppWorkflow"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/AppWorkflow"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                    description:
                        ""
            tags: ["AppWorkflow"]
        put:
            operationId: putAppWorkflow
            parameters:
                - in: path
                  name: appId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AppWorkflow"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/AppWorkflow"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AppWorkflow"
                    description:
                        ""
            tags: ["AppWorkflow"]
    "/apps/{appId}/app-workflows/data-record-links":
        post:
            operationId: postAppAppWorkflowDataRecordLinksPage
            parameters:
                - in: path
                  name: appId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataRecordIds"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/DataRecordIds"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/AppWorkflowDataRecordLink"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/AppWorkflowDataRecordLink"
                                type: array
                    description:
                        ""
            tags: ["AppWorkflowDataRecordLink"]