apiDir: "../headless-commerce-admin-order-api/src/main/java"
apiPackagePath: "com.liferay.headless.commerce.admin.order"
application:
    baseURI: "/headless-commerce-admin-order"
    className: "HeadlessCommerceAdminOrderApplication"
    name: "Liferay.Headless.Commerce.Admin.Order"
author: "Alessio Antonio Rendina"
clientDir: "../headless-commerce-admin-order-client/src/main/java"
forcePredictableSchemaPropertyName: false
testDir: "../headless-commerce-admin-order-test/src/testIntegration/java"