components:
    schemas:
        Document:
            description: "https://www.schema.org/Document"
            type: object
info:
    description: ""
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: "1.0.0"
openapi: "3.0.1"