components:
  schemas:
    AggregateRating:
      description: https://www.schema.org/AggregateRating
      properties:
        bestRating:
          type: number
        id:
          format: int64
          type: integer
        ratingCount:
          type: number
        ratingValue:
          type: number
        self:
          format: uri
          type: string
        worstRating:
          type: number
      type: object
    Comment:
      description: https://www.schema.org/Comment
      properties:
        comments:
          items:
            $ref: "#/components/schemas/Comment"
          type: array
        creator:
          $ref: "#/components/schemas/Creator"
        id:
          format: int64
          type: integer
        self:
          format: uri
          type: string
        text:
          type: string
      type: object
    ContentDocument:
      description: https://www.schema.org/ContentDocument
      properties:
        contentUrl:
          format: uri
          type: string
        creator:
          $ref: "#/components/schemas/Creator"
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        encodingFormat:
          type: string
        fileExtension:
          type: string
        id:
          format: int64
          type: integer
        self:
          format: uri
          type: string
        sizeInBytes:
          type: number
        title:
          type: string
      type: object
    ContentStructure:
      description: https://www.schema.org/ContentStructure
      properties:
        availableLanguages:
          items:
            type: string
          type: array
        contentSpace:
          format: int64
          type: integer
        creator:
          $ref: "#/components/schemas/Creator"
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        description:
          type: string
        id:
          format: int64
          type: integer
        name:
          type: string
        self:
          format: uri
          type: string
      type: object
    Creator:
      description: https://www.schema.org/Creator
      properties:
        additionalName:
          type: string
        alternateName:
          type: string
        email:
          type: string
        familyName:
          type: string
        givenName:
          type: string
        id:
          format: int64
          type: integer
        image:
          format: uri
          type: string
        jobTitle:
          type: string
        name:
          type: string
        profileURL:
          format: uri
          type: string
        self:
          format: uri
          type: string
      type: object
    StructuredContent:
      description: https://www.schema.org/StructuredContent
      properties:
        aggregateRating:
          $ref: "#/components/schemas/AggregateRating"
        availableLanguages:
          items:
            type: string
          type: array
        category:
          items:
            format: int64
            type: integer
          type: array
        comment:
          items:
            $ref: "#/components/schemas/Comment"
          type: array
        contentSpace:
          format: int64
          type: integer
        contentStructure:
          $ref: "#/components/schemas/ContentStructure"
        creator:
          $ref: "#/components/schemas/Creator"
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        datePublished:
          format: date-time
          type: string
        description:
          type: string
        id:
          format: int64
          type: integer
        keywords:
          items:
            type: string
          type: array
        lastReviewed:
          type: string
        renderedContentsByTemplate:
          description: https://www.schema.org/templates
          properties:
            id:
              format: int64
              type: integer
            renderedContent:
              type: string
            self:
              format: uri
              type: string
            template:
              type: string
          type: object
        self:
          format: uri
          type: string
        title:
          type: string
        values:
          description: https://www.schema.org/ContentFieldValue
          properties:
            dataType:
              type: string
            filterAndSortIdentifier:
              type: string
            id:
              format: int64
              type: integer
            inputControl:
              type: string
            label:
              type: string
            name:
              type: string
            self:
              format: uri
              type: string
            value:
              anyOf:
                - properties:
                    data:
                      type: string
                - properties:
                    document:
                      $ref: "#/components/schemas/ContentDocument"
                - properties:
                    geo:
                      description: https://www.schema.org/GeoCoordinates
                      properties:
                        id:
                          format: int64
                          type: integer
                        latitude:
                          type: number
                        longitude:
                          type: number
                        self:
                          format: uri
                          type: string
                      type: object
                - properties:
                    link:
                      format: uri
                      type: string
                - properties:
                    structuredContent:
                      $ref: "#/components/schemas/StructuredContent"
          type: object
      type: object
info:
  description: ""
  title: ""
  version: 1.0.0
openapi: 3.0.1
paths:
  "/aggregate-rating/{aggregate-rating-id}":
    get:
      parameters:
        - in: path
          name: aggregate-rating-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AggregateRating"
          description: ""
  "/comment/{comment-id}":
    get:
      parameters:
        - in: path
          name: comment-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
          description: ""
  "/comment/{comment-id}/comment":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: comment-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""
  "/content-document/{content-document-id}":
    delete:
      parameters:
        - in: path
          name: content-document-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
    get:
      parameters:
        - in: path
          name: content-document-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentDocument"
          description: ""
  "/content-space/{content-space-id}/content-structures":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ContentStructure"
                type: array
          description: ""
  "/content-space/{content-space-id}/structured-contents":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/StructuredContent"
                type: array
          description: ""
    post:
      parameters:
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
  "/content-space/{content-space-id}/structured-contents/batch-create":
    post:
      parameters:
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
  "/content-structures/{content-structures-id}":
    get:
      parameters:
        - in: path
          name: content-structures-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentStructure"
          description: ""
  "/creator/{creator-id}":
    get:
      parameters:
        - in: path
          name: creator-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Creator"
          description: ""
  "/structured-contents/{structured-contents-id}":
    delete:
      parameters:
        - in: path
          name: structured-contents-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
    get:
      parameters:
        - in: path
          name: structured-contents-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
    put:
      parameters:
        - in: path
          name: structured-contents-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
  "/structured-contents/{structured-contents-id}/comment":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: structured-contents-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""