apiDir: "../headless-commerce-punchout-api/src/main/java"
apiPackagePath: "com.liferay.headless.commerce.punchout"
application:
    baseURI: "headless-commerce-punchout"
    className: "HeadlessCommercePunchOutApplication"
    name: "Liferay.Headless.Commerce.PunchOut"
author: "Jaclyn Ong"
forcePredictableSchemaPropertyName: false
generateGraphQL: false